const LOGIN_SUCCESS = 1;
const SIGN_UP_SUCCESS = 2;
const ERROR_VALIDATION_FAILED = 3;
const ERROR_SOMETHING_BAD_HAPPEND = 4;
const ERROR_INVALID_EMAIL_PASSWORD = 5;
const ERROR_EMAIL_ALREADY_EXISTS = 6;

module.exports = {
  LOGIN_SUCCESS,
  SIGN_UP_SUCCESS,
  ERROR_VALIDATION_FAILED,
  ERROR_SOMETHING_BAD_HAPPEND,
  ERROR_INVALID_EMAIL_PASSWORD,
  ERROR_EMAIL_ALREADY_EXISTS,
};
